[target.riscv32imac-unknown-none-elf]
runner = "qemu-system-riscv32 -machine virt -nographic -semihosting-config enable=on,target=native -monitor stdio -serial none -bios"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -nographic -semihosting-config enable=on,target=native -monitor stdio -serial none -bios"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]


